// Copyright (C) 2025-2026 Virtastic - https://virtastic.app
// SPDX-License-Identifier: GPL-3.0-or-later | part of openmw-web
// Phase 3.5.2b: the approved-mod whitelist, and the tier rule that decides what has to
// MATCH between players.
//
// The distinction that matters is not "vanilla vs modded", it is whether a file changes
// something the simulation reads:
//
//   content  (.esp/.esm/.omwaddon)  records — NPCs, stats, cells, scripts. Two players
//            with different content plugins disagree about the game itself, so these must
//            match across a world and the gate refuses a mismatch.
//   cosmetic (meshes, textures, animations)  Project Atlas, MOP's optimized meshes,
//            Weapon Sheathing. They change what a player SEES, nothing the server or any
//            other client reads — so they are allowed to differ, and one player running
//            them while another does not is a supported, ordinary state.
//
// Refusing cosmetic differences would be the easy implementation and the wrong product: it
// would mean nobody can try a texture pack without every friend installing it first.
//
// The manifest is generated by wasm-build/gen-mod-manifest.mjs from archives the operator
// downloaded; it holds hashes only, never mod content (docs/LEGAL.md §7).

import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { log } from '../log';

export interface ModFileEntry {
  path: string;
  size: number;
  sha256: string;
  tier: 'content' | 'cosmetic';
}

export interface ModEntry {
  id: string;
  name: string;
  order: number;
  nexus?: string;
  source?: string;
  variantNote?: string;
  settings?: Record<string, string>;
  contentFiles: string[];
  fileCount: number;
  totalBytes: number;
  files: ModFileEntry[];
}

export interface ModManifestDoc {
  generatedFrom: string[];
  mods: ModEntry[];
}

export class ModWhitelist {
  private readonly bySha = new Map<string, { mod: ModEntry; file: ModFileEntry }>();
  private readonly byBasename = new Map<string, ModFileEntry[]>();
  readonly mods: readonly ModEntry[];

  private constructor(doc: ModManifestDoc) {
    this.mods = [...doc.mods].sort((a, b) => a.order - b.order);
    for (const mod of this.mods) {
      for (const file of mod.files) {
        this.bySha.set(file.sha256.toLowerCase(), { mod, file });
        const base = file.path.split('/').pop()!.toLowerCase();
        const list = this.byBasename.get(base) ?? [];
        list.push(file);
        this.byBasename.set(base, list);
      }
    }
  }

  get empty(): boolean {
    return this.bySha.size === 0;
  }

  // Is this exact file an approved one? Hash, not name: a file called Morrowind.esm with
  // different bytes is a different file, and that is the whole point of the check.
  lookup(sha256: string): { mod: ModEntry; file: ModFileEntry } | undefined {
    return this.bySha.get(sha256.toLowerCase());
  }

  // A file whose NAME we know but whose bytes we do not. Almost always the wrong variant
  // of a mod that ships several (Weapon Sheathing's MWSE vs OpenMW builds are the reason
  // this exists) — worth saying so rather than reporting an anonymous "unknown file",
  // which sends the player looking in the wrong place for an hour.
  knownName(path: string): boolean {
    return this.byBasename.has(path.split('/').pop()!.toLowerCase());
  }

  // Name-based tier lookup for the content gate: a manifest entry only carries a file
  // NAME, so the gate asks "is a file called this an approved cosmetic one".
  lookupName(name: string): 'cosmetic' | 'content' | undefined {
    const base = name.split('/').pop()!.toLowerCase();
    const hits = this.byBasename.get(base);
    if (!hits || hits.length === 0) return undefined;
    // If any variant with this name is record-bearing, treat the name as content: the
    // safe direction is to REQUIRE a match, never to wave through a plugin.
    return hits.some((f) => f.tier === 'content') ? 'content' : 'cosmetic';
  }

  // The settings.cfg keys the approved mods need. Weapon Sheathing without these loads its
  // meshes and sheathes nothing, which presents as "the mod is broken".
  requiredSettings(): Record<string, string> {
    const out: Record<string, string> = {};
    for (const mod of this.mods) Object.assign(out, mod.settings ?? {});
    return out;
  }

  // Reads exactly the paths it is given, in order, and stops at the first that loads.
  // Explicit rather than cwd-relative: a whitelist that changes depending on where the
  // process was launched from is a rule nobody can reason about, and this one decides
  // whether a player is let in.
  //
  // Empty (no mods approved = vanilla only) is a valid, common answer; a missing manifest
  // must never fail boot.
  static async load(...dirs: string[]): Promise<ModWhitelist> {
    for (const dir of dirs) {
      const candidate = join(dir, 'mod-manifest.json');
      try {
        const doc = JSON.parse(await readFile(candidate, 'utf8')) as ModManifestDoc;
        const wl = new ModWhitelist(doc);
        log('info', 'modwhitelist.loaded', { mods: wl.mods.length, files: wl.bySha.size, from: candidate });
        return wl;
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
          log('error', 'modwhitelist.bad_file', { path: candidate, error: String(err) });
        }
      }
    }
    return new ModWhitelist({ generatedFrom: [], mods: [] });
  }

  static fromDoc(doc: ModManifestDoc): ModWhitelist {
    return new ModWhitelist(doc);
  }
}
