// Copyright (C) 2025-2026 Virtastic - https://virtastic.app
// SPDX-License-Identifier: GPL-3.0-or-later | part of openmw-web
// Replacing a stock data file (Morrowind/Tribunal/Bloodmoon .esm/.bsa) with a community copy,
// through the mod manager. Opt-in twice (config + a tick on the mod); default behaviour unchanged.

import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer, type Server } from 'node:http';

import { emptyDoc, readModDoc, resolveMods, writeModDoc, type InstalledMod, type ModDoc } from '../src/core/mods';
import { buildPeerCfg, detectGameData, hashContentFiles } from '../src/core/gamedata';
import { ContentGate } from '../src/core/manifest';
import { saveModOrder } from '../src/net/admin/mod-install';
import { modsView } from '../src/net/admin/api-mods';
import { mwDataRoutes } from '../src/net/mwdata-routes';
import { loadConfig } from '../src/config';

const tmp = (): string => mkdtempSync(join(tmpdir(), 'swap-'));
const sha = (s: string): string => createHash('sha256').update(s).digest('hex');
const mod = (over: Partial<InstalledMod> & { slug: string }): InstalledMod => ({
  name: over.slug, archive: '', source: '', installedAt: '', enabled: true,
  plugins: [], archives: [], files: 1, bytes: 1, ...over,
});
const swapMod = (over: Partial<InstalledMod> = {}): InstalledMod => mod({
  slug: 'community', name: 'Community Base',
  plugins: [{ file: 'Morrowind.esm', enabled: true }, { file: 'Extra.esp', enabled: true }],
  archives: ['Morrowind.bsa'], replaces: ['Morrowind.esm', 'Morrowind.bsa'], ...over,
});
const docOf = (...mods: InstalledMod[]): ModDoc => ({ ...emptyDoc(), mods });
const ON = { allowStockSwap: true };

// --- resolution -------------------------------------------------------------------------------

test('a mod shipping a stock-named file is left out whole unless the swap is approved twice', () => {
  const d = docOf(swapMod(), mod({ slug: 'other', plugins: [{ file: 'Other.esp', enabled: true }] }));
  // Gate off (the default) -- even with the tick set on the mod.
  const off = resolveMods(d);
  assert.deepEqual(off.dataDirs, ['mods/other'], 'the folder must not be a data= root: it would shadow the stock name');
  assert.deepEqual(off.content, ['Other.esp']);
  assert.deepEqual(off.refused.map((r) => [r.slug, r.files]), [['community', ['Morrowind.esm', 'Morrowind.bsa']]]);
  assert.deepEqual(off.swaps, []);
  // Gate on, tick missing.
  const untick = resolveMods(docOf(swapMod({ replaces: undefined })), ON);
  assert.deepEqual(untick.dataDirs, []);
  assert.equal(untick.refused.length, 1);
  // Gate on, only one of the two shadowing files ticked: still refused whole.
  assert.equal(resolveMods(docOf(swapMod({ replaces: ['Morrowind.esm'] })), ON).refused.length, 1);
});

test('an approved swap keeps the stock content=/archive lines and adds the folder as a later data= root', () => {
  const s = resolveMods(docOf(swapMod()), ON);
  assert.deepEqual(s.dataDirs, ['mods/community'], 'later than the base data=, so the engine resolves the name to the copy');
  assert.deepEqual(s.content, ['Extra.esp'], 'Morrowind.esm is NOT emitted a second time');
  assert.deepEqual(s.archives, [], 'Morrowind.bsa is NOT registered a second time');
  assert.deepEqual(s.swaps.map((x) => [x.file, x.slug]), [['Morrowind.esm', 'community'], ['Morrowind.bsa', 'community']]);
  assert.deepEqual(s.refused, []);
});

test('a stock-named plugin that is switched off still shadows, so it still needs the swap', () => {
  const m = swapMod({ plugins: [{ file: 'Tribunal.esm', enabled: false }], archives: [], replaces: undefined });
  assert.equal(resolveMods(docOf(m), ON).refused.length, 1);
});

test('UNCHANGED DEFAULT: a doc with no stock-named files resolves and writes the same cfg as before', () => {
  const d = docOf(
    mod({ slug: 'tr', plugins: [{ file: 'TR_Mainland.esm', enabled: true }], archives: ['TR.bsa'] }),
    mod({ slug: 'p', plugins: [{ file: 'P.esp', enabled: true }] }));
  for (const opts of [undefined, ON]) {
    const s = resolveMods(d, opts);
    assert.deepEqual(s.dataDirs, ['mods/tr', 'mods/p']);
    assert.deepEqual(s.content, ['TR_Mainland.esm', 'P.esp']);
    assert.deepEqual(s.archives, ['TR.bsa']);
    assert.deepEqual([s.swaps, s.refused], [[], []]);
  }
  const gd = tmp();
  for (const f of ['Morrowind.esm', 'Morrowind.bsa']) writeFileSync(join(gd, f), 'x');
  assert.equal(buildPeerCfg(detectGameData(gd), '/res', resolveMods(d)),
    `# GENERATED by openmw-mp for the Phase H simulation peer. Edits are overwritten.\n`
    + `data=${gd}\ndata=${join(gd, 'mods/tr')}\ndata=${join(gd, 'mods/p')}\ncontent=Morrowind.esm\n`
    + `content=TR_Mainland.esm\ncontent=P.esp\ncontent=mp.omwscripts\nfallback-archive=Morrowind.bsa\n`
    + `fallback-archive=TR.bsa\nresources=/res\n`);
});

// --- persistence ------------------------------------------------------------------------------

test('replaces round-trips through modlist.json; non-stock names are dropped on read', () => {
  const d = tmp();
  writeModDoc(d, docOf(swapMod({ replaces: ['Morrowind.esm', 'Evil.esm'] })));
  assert.deepEqual(readModDoc(d).mods[0]!.replaces, ['Morrowind.esm']);
  writeModDoc(d, docOf(mod({ slug: 'plain' })));
  assert.equal('replaces' in readModDoc(d).mods[0]!, false, 'a mod without a swap has no field at all');
});

test('saveModOrder: refused while the feature is off, or for a file the mod does not ship', () => {
  const d = tmp();
  writeModDoc(d, docOf(swapMod({ replaces: undefined })));
  const off = saveModOrder(d, [{ slug: 'community', replaces: ['Morrowind.esm'] }]);
  assert.equal(off.ok, false);
  assert.match(off.ok ? '' : off.error, /allowStockSwap/);
  assert.equal(readModDoc(d).mods[0]!.replaces, undefined, 'nothing was saved');

  const wrong = saveModOrder(d, [{ slug: 'community', replaces: ['Tribunal.esm'] }], true);
  assert.equal(wrong.ok, false);
  assert.match(wrong.ok ? '' : wrong.error, /does not ship Tribunal\.esm/);
  assert.equal(saveModOrder(d, [{ slug: 'community', replaces: ['Extra.esp'] }], true).ok, false);
});

test('saveModOrder: a valid tick is stored, an absent field keeps it, an empty list clears it', () => {
  const d = tmp();
  writeModDoc(d, docOf(swapMod({ replaces: undefined })));
  assert.ok(saveModOrder(d, [{ slug: 'community', replaces: ['morrowind.esm'] }], true).ok);
  assert.deepEqual(readModDoc(d).mods[0]!.replaces, ['Morrowind.esm'], 'stored with the mod\'s own spelling');
  assert.ok(saveModOrder(d, [{ slug: 'community' }]).ok, 'an old page that never sends the field');
  assert.deepEqual(readModDoc(d).mods[0]!.replaces, ['Morrowind.esm']);
  assert.ok(saveModOrder(d, [{ slug: 'community', replaces: [] }]).ok, 'clearing is allowed even with the feature off');
  assert.equal(readModDoc(d).mods[0]!.replaces, undefined);
});

test('the dashboard view says what is swapped and what was left out', () => {
  const d = tmp();
  const gd = join(d, 'gamedata'); mkdirSync(gd);
  writeModDoc(d, docOf(swapMod()));
  const off = modsView(gd, d) as { allowStockSwap: boolean; refused: { slug: string }[]; swaps: unknown[] };
  assert.equal(off.allowStockSwap, false);
  assert.deepEqual(off.refused.map((r) => r.slug), ['community']);
  const on = modsView(gd, d, undefined, true) as typeof off;
  assert.equal(on.allowStockSwap, true);
  assert.deepEqual(on.refused, []);
  assert.equal(on.swaps.length, 2);
});

// --- the world's hashes -----------------------------------------------------------------------

test('the world hashes the swapped bytes, and a refused copy never hashes over the stock file', () => {
  const gd = tmp();
  for (const f of ['Morrowind.esm', 'Morrowind.bsa', 'Tribunal.esm', 'Tribunal.bsa', 'Bloodmoon.esm', 'Bloodmoon.bsa']) {
    writeFileSync(join(gd, f), `stock-${f}`);
  }
  mkdirSync(join(gd, 'mods', 'community'), { recursive: true });
  writeFileSync(join(gd, 'mods', 'community', 'Morrowind.esm'), 'community-bytes');
  const data = detectGameData(gd);
  const doc = docOf(swapMod());

  const approved = hashContentFiles(data, doc.mods, resolveMods(doc, ON));
  assert.equal(approved.get('morrowind.esm'), sha('community-bytes'));
  assert.equal(approved.get('tribunal.esm'), sha('stock-Tribunal.esm'));

  const refused = hashContentFiles(data, doc.mods, resolveMods(doc));
  assert.equal(refused.get('morrowind.esm'), sha('stock-Morrowind.esm'), 'the copy is not loaded, so it is not the world\'s');
});

// --- the gate ---------------------------------------------------------------------------------

const manifest = (h?: string) => [
  { name: 'Morrowind.esm', size: 0, idx: 0, ...(h ? { sha256: h } : {}) },
  { name: 'Tribunal.esm', size: 0, idx: 1 },
];

function gate(mode: 'names' | 'strict' | 'off', swapped: boolean): ContentGate {
  const g = new ContentGate(mode);
  g.hashes = () => new Map([['morrowind.esm', sha('community-bytes')]]);
  if (swapped) g.swapped = () => new Map([['morrowind.esm', 'Community Base']]);
  g.setAuthoritative(manifest());
  return g;
}

test('a client reporting a different hash for a swapped file is refused, naming file and mod', () => {
  for (const mode of ['names', 'strict'] as const) {
    const r = gate(mode, true).check(manifest(sha('stock-Morrowind.esm')));
    assert.equal(r.ok, false, mode);
    assert.match(r.ok ? '' : r.detail, /Morrowind\.esm \(this world runs the community copy from Community Base\)/);
    assert.match(r.ok ? '' : r.detail, /operator/);
  }
});

test('the matching hash passes; a client that reports none still passes under names', () => {
  assert.equal(gate('names', true).check(manifest(sha('community-bytes'))).ok, true);
  assert.equal(gate('names', true).check(manifest()).ok, true, 'server-hosted data reports none and is served the swap');
  assert.equal(gate('strict', true).check(manifest()).ok, false, 'strict still refuses a client that cannot prove its files');
});

test('UNCHANGED DEFAULT: with no swap the gate behaves exactly as before, and off stays off', () => {
  // A stock hash against a world with no swap: names mode never compared hashes, and still does not.
  assert.equal(gate('names', false).check(manifest(sha('anything'))).ok, true);
  assert.equal(gate('off', true).check(manifest(sha('stock-Morrowind.esm'))).ok, true);
  // strict's own refusal keeps its own wording.
  const r = gate('strict', false).check(manifest(sha('other')));
  assert.match(r.ok ? '' : r.detail, /does not match this world's copy/);
});

// --- what the browser is told -----------------------------------------------------------------

async function sidecar(doc: ModDoc, allow: boolean | undefined): Promise<{ status: number; body: any }> {
  const dir = tmp();
  writeFileSync(join(dir, 'Morrowind.esm'), 'x');
  mkdirSync(join(dir, 'mods', 'community'), { recursive: true });
  writeFileSync(join(dir, 'mods', 'community', 'Morrowind.esm'), 'y');
  const route = mwDataRoutes({
    gameDataDir: dir, deliveryModel: () => 'serve', modDoc: () => doc,
    ...(allow === undefined ? {} : { allowStockSwap: () => allow }),
  });
  const srv: Server = createServer((req, res) => {
    void (async () => { if (!(await route(req, res, new URL(req.url ?? '/', 'http://x')))) { res.writeHead(404); res.end(); } })();
  });
  await new Promise<void>((r) => srv.listen(0, '127.0.0.1', r));
  try {
    const r = await fetch(`http://127.0.0.1:${(srv.address() as { port: number }).port}/mwdata-mods.json`);
    return { status: r.status, body: r.status === 200 ? await r.json() : null };
  } finally { await new Promise<void>((r) => srv.close(() => r())); }
}

test('the sidecar mounts an approved swap without repeating the stock lines, and hides a refused mod', async () => {
  const doc = docOf(swapMod(), mod({ slug: 'p', plugins: [{ file: 'P.esp', enabled: true }] }));
  const on = await sidecar(doc, true);
  const m = on.body.mods.find((x: { slug: string }) => x.slug === 'community');
  assert.deepEqual(m.plugins, ['Extra.esp']);
  assert.deepEqual(m.archives, []);
  assert.deepEqual(on.body.content, ['Extra.esp', 'P.esp']);
  assert.deepEqual(on.body.swaps.map((s: { file: string }) => s.file), ['Morrowind.esm', 'Morrowind.bsa']);

  for (const allow of [false, undefined]) {
    const off = await sidecar(doc, allow);
    assert.deepEqual(off.body.mods.map((x: { slug: string }) => x.slug), ['p'], 'not mounted: its folder would shadow Morrowind.esm');
    assert.deepEqual(off.body.content, ['P.esp']);
    assert.deepEqual(off.body.swaps, []);
  }
});

test('UNCHANGED DEFAULT: an ordinary mod list is served exactly as before', async () => {
  const s = await sidecar(docOf(mod({ slug: 'community', plugins: [{ file: 'A.esp', enabled: true }] })), false);
  assert.deepEqual(s.body.mods.map((x: { plugins: string[] }) => x.plugins), [['A.esp']]);
  assert.deepEqual(s.body.content, ['A.esp']);
});

// --- config -----------------------------------------------------------------------------------

test('[content] allowStockSwap defaults to false and is switchable', () => {
  assert.equal(loadConfig(tmp()).content.allowStockSwap, false);
  assert.equal(loadConfig(tmp(), { content: { allowStockSwap: true } }).content.allowStockSwap, true);
  assert.equal(loadConfig(tmp()).content.enforce, 'names', 'the neighbouring default is untouched');
});
